### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by HyperRaccoon13** [Erdragh/ProjectTable#16] opened 2023-08-12 16:40 UTC
Placeing a create funnel on the table
then crafting an item will cause the item to be crafted but the ingredients to be dropped
onl

https://github.com/Erdragh/ProjectTableRefabricated/assets/68512889/89d6f7a5-01d2-4f23-8b2c-acd7596d5bc5

seems to only work when dragging items and sometimes when useing REI to quick craft

**Comment by Erdragh** [comment] 2023-08-12 16:42
Alright, I can already see where this is coming from. The 9 slots used for the input are the same container that is used for the extra storage. 

I'll see how easy this is to fix.

Meanwhile, test if this also happens with the YTTR Project Table, because that's what I based this on very heavily

**Comment by Infern0-b0b** [comment] 2023-08-12 18:03
I can confirm that this acts the same way on the YTTR Project Table. For both tables, if you exit the Ui and then go back in, then the item dupe won't work, but I don't think that is really relevant given the fix that you are going to apply to it.

**Comment by Erdragh** [comment] 2023-09-07 14:46
Fixed in #18

**Closed as completed by Erdragh** 2023-09-07 14:46 UTC
Labels: bug
